name: Union Bot

on:
  schedule:
    - cron: '0 1 * * *' # Setiap hari pukul 08:00 WIB
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/union.yml

jobs:
  start-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch GitHub User Info
        run: |
          GIT_NAME=$(curl -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         https://api.github.com/user | jq -r '.login')

          GIT_EMAIL=$(curl -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/user | jq -r '.email')

          if [ -z "$GIT_EMAIL" ] || [ "$GIT_EMAIL" == "null" ]; then
            GIT_EMAIL="${GIT_NAME}@users.noreply.github.com"
          fi

          echo "GIT_NAME=$GIT_NAME" >> $GITHUB_ENV
          echo "GIT_EMAIL=$GIT_EMAIL" >> $GITHUB_ENV

      - name: Fetch wallet.json
        run: |
          echo "ðŸ”„ Fetching wallet.json..."
          curl -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
               -H "Accept: application/vnd.github.v3" \
               https://api.github.com/repos/${GIT_NAME}/private/contents/wallet.json \
               | jq -r '.content' | base64 --decode > wallet.json

          if ! jq empty wallet.json >/dev/null 2>&1; then
            echo "âš ï¸ Invalid JSON detected! Replacing with an empty array."
            echo "[]" > wallet.json
          fi

      - name: Download and Unzip union_daily.zip
        run: |
          echo "ðŸ“¦ Downloading union_daily.zip..."
          wget https://bash.ryanda.xyz/union_daily.zip -O union_daily.zip

          echo "ðŸ§© Unzipping union_daily.zip to current directory..."
          unzip -o union_daily.zip

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: |
          node babylon_holesky.js || true
          node babylon_xion.js || true
          node sepolia_babylon.js || true
          node sepolia_holesky.js || true

      - name: Update Timestamp File
        run: |
          export TZ="Asia/Jakarta"
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time (UTC+7)" > TIMESTAMP.txt
	  git add TIMESTAMP.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "$GIT_EMAIL"
          git config user.name "$GIT_NAME"

      - name: Prepare Commit
        run: |
          export TZ="Asia/Jakarta"
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          commit_message="Update at $current_time (UTC+7)"

          git add TIMESTAMP.txt
          git commit -m "$commit_message" || echo "No changes to commit."

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: rm -f wallet.json union.zip
